import java.awt.Color;
import java.awt.Graphics;
import javax.swing.*;

public class NewJApplet extends javax.swing.JFrame {

    // Constructor → call init() when window is created
    public NewJApplet() {
        init();
    }

    // Main method → entry point to run in JDK 25
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new NewJApplet().setVisible(true);
        });
    }

   public void init() {
    try {
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    initComponents();

    // 🔑 Add listeners here
   btn1.addActionListener(e -> {
    etiqueta.setForeground(Color.YELLOW);
    jLabel1.setText("El botón Amarillo ha sido presionado");
});

btn2.addActionListener(e -> {
    etiqueta.setForeground(Color.BLUE);
    jLabel1.setText("El botón Azul ha sido presionado");
});

btn3.addActionListener(e -> {
    etiqueta.setForeground(Color.RED);
    jLabel1.setText("El botón Rojo ha sido presionado");
});
}

@Override
public void paint(Graphics g) {
    super.paint(g); // draw all the components normally
}

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        etiqueta = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        btn2 = new java.awt.Button();
        btn3 = new java.awt.Button();
        btn1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        etiqueta.setAlignment(java.awt.Label.CENTER);
        etiqueta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiqueta.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        etiqueta.setMinimumSize(new java.awt.Dimension(50, 20));
        etiqueta.setName(""); // NOI18N
        etiqueta.setPreferredSize(new java.awt.Dimension(100, 20));
        etiqueta.setText("Servicio Nacional De Aprendizaje");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btn2.setBackground(new java.awt.Color(0, 0, 0));
        btn2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(240, 240, 240));
        btn2.setLabel("Azul");
        jPanel1.add(btn2);

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(240, 240, 240));
        btn3.setLabel("Rojo");
        jPanel1.add(btn3);

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(240, 240, 240));
        btn1.setLabel("Amarillo");
        jPanel1.add(btn1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El botón X ha sido presionado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(393, 393, 393))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void btn1ActionPerformed(java.awt.event.ActionEvent evt){etiqueta.setForeground(Color.yellow);                          
        // TODO add your handling code here:
    }               
private void btn2ActionPerformed(java.awt.event.ActionEvent evt){etiqueta.setForeground(Color.blue);                          
        // TODO add your handling code here:
    }   
private void btn3ActionPerformed(java.awt.event.ActionEvent evt){etiqueta.setForeground(Color.red);                          
        // TODO add your handling code here:
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn1;
    private java.awt.Button btn2;
    private java.awt.Button btn3;
    private java.awt.Label etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
